"""
Enclave Client — runs on the HOST OS (FastAPI app side).

This module provides the communication layer between the FastAPI application
(running on the EC2 host) and the Nitro Enclave (running in hardware isolation).

Communication flow:
  1. FastAPI receives a detection request from the user
  2. This client encrypts the payload with AES-256-GCM using the enclave's shared key
  3. Sends the ciphertext over vsock (Virtual Socket) to CID=16, port=5000
  4. Enclave decrypts, runs inference, encrypts response, sends it back
  5. This client decrypts the response and returns it to FastAPI

In DEMO/MOCK mode (no actual AWS Nitro hardware), this falls back to calling the
enclave functions directly — simulating what the enclave would do.
"""

import os
import json
import socket
import logging
from typing import Dict, Any, Optional, Union

logger = logging.getLogger("vas.enclave_client")

# ─── Configuration ─────────────────────────────────────────────────
# Default vsock parameters for Nitro Enclave
ENCLAVE_CID: int = 16       # Fixed CID for the primary enclave
ENCLAVE_PORT: int = 5000    # Must match enclave_server.py port
VSOCK_TIMEOUT: float = 5.0  # Seconds before timing out
MOCK_MODE: bool = os.environ.get("VAS_ENCLAVE_MOCK", "true").lower() == "true"

# Shared AES-256-GCM key (exchanged via attestation in production)
# In production, this key is obtained via the Nitro Attestation process:
#   1. Enclave generates a key during boot
#   2. Host requests attestation document from enclave
#   3. Host verifies enclave identity via AWS KMS
#   4. Enclave securely transmits the AES key to the host
#   5. Subsequent communication uses this key for AES-256-GCM
SHARED_KEY: Optional[bytes] = None


def _get_shared_key() -> bytes:
    """Get or derive the shared AES-256-GCM key."""
    global SHARED_KEY
    if SHARED_KEY is None:
        if MOCK_MODE:
            # In mock mode, match the key generated by enclave_server.py
            # Generate deterministically to match enclave's key
            SHARED_KEY = b"\x00" * 32  # Placeholder — replaced by actual key exchange
            logger.warning("MOCK MODE: Using placeholder shared key (not secure)")
        else:
            # In production, obtain via attestation key exchange
            raise RuntimeError(
                "No shared key available. Run attestation handshake first. "
                "Call /api/v1/enclave/attestation to perform key exchange."
            )
    return SHARED_KEY


def set_shared_key(key: bytes) -> None:
    """Set the shared AES key after attestation handshake."""
    global SHARED_KEY
    if len(key) != 32:
        raise ValueError("AES-256 key must be exactly 32 bytes")
    SHARED_KEY = key
    logger.info("Shared AES-256 key set (%d bytes)", len(key))


def _encrypt_payload(payload: Dict[str, Any]) -> bytes:
    """Encrypt a JSON payload with AES-256-GCM for enclave."""
    try:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    except ImportError:
        return _mock_encrypt(payload)

    key = _get_shared_key()
    aesgcm = AESGCM(key)
    nonce = os.urandom(12)
    plaintext = json.dumps(payload).encode("utf-8")
    ciphertext = aesgcm.encrypt(nonce, plaintext, None)
    return nonce + ciphertext


def _decrypt_response(data: bytes) -> Dict[str, Any]:
    """Decrypt AES-256-GCM response from enclave."""
    try:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    except ImportError:
        return _mock_decrypt(data)

    key = _get_shared_key()
    aesgcm = AESGCM(key)
    nonce = data[:12]
    ciphertext = data[12:]
    plaintext = aesgcm.decrypt(nonce, ciphertext, None)
    return json.loads(plaintext.decode("utf-8"))


def _mock_encrypt(payload: Dict[str, Any]) -> bytes:
    """Mock encryption for demo when cryptography not available."""
    plaintext = json.dumps(payload).encode("utf-8")
    return b"MOCK:" + plaintext


def _mock_decrypt(data: bytes) -> Dict[str, Any]:
    """Mock decryption for demo."""
    if data.startswith(b"MOCK:"):
        return json.loads(data[5:].decode("utf-8"))
    return json.loads(data.decode("utf-8"))


# ─── vsock Communication ──────────────────────────────────────────

def call_enclave_vsock(payload: Dict[str, Any]) -> Dict[str, Any]:
    """
    Send encrypted payload to the Nitro Enclave over vsock and receive response.
      # noqa: W293
    Args:
        payload: Dictionary with action and parameters
                 e.g. {"action": "classify_sms", "sms_text": "..."}
      # noqa: W293
    Returns:
        Decrypted response dictionary from the enclave
      # noqa: W293
    Raises:
        ConnectionError: If enclave is unreachable
        TimeoutError: If response takes too long
    """
    encrypted_request = _encrypt_payload(payload)
      # noqa: E114,E116,W293
    # vsock is Linux-only (not available on Windows/macOS)
    # In production on AWS Nitro EC2, socket.AF_VSOCK is available
    # In dev/demo mode, use the mock fallback
    try:
        vsock_family = socket.AF_VSOCK  # type: ignore[attr-defined]
    except AttributeError:
        raise ConnectionError(
            "vsock is not available on this platform. "
            "Set VAS_ENCLAVE_MOCK=true for mock mode, "
            "or run on AWS Nitro EC2 with Nitro Enclaves enabled."
        )
      # noqa: E114,W293
    sock = socket.socket(vsock_family, socket.SOCK_STREAM)  # type: ignore[arg-type]
    sock.settimeout(VSOCK_TIMEOUT)
      # noqa: E114,E116,W293
    try:
        logger.debug(
            "Connecting to enclave vsock (CID=%d, port=%d)...",
            ENCLAVE_CID, ENCLAVE_PORT,
        )
        sock.connect((ENCLAVE_CID, ENCLAVE_PORT))
        sock.sendall(encrypted_request)
          # noqa: E114,E116,W293
        response = sock.recv(65536)
        if not response:
            raise ConnectionError("Empty response from enclave")
          # noqa: E114,W293
        result = _decrypt_response(response)
        logger.debug("Enclave response received (action=%s)", payload.get("action"))
        return result
          # noqa: E114,E116,W293
    except socket.timeout:
        raise TimeoutError(
            f"Enclave vsock timeout after {VSOCK_TIMEOUT}s "
            f"(CID={ENCLAVE_CID}, port={ENCLAVE_PORT})"
        )
    except OSError as e:
        raise ConnectionError(
            f"Enclave unreachable via vsock: {e}. "
            "Ensure Nitro Enclaves is running and vsock is configured."
        )
    finally:
        sock.close()


# ─── Mock Enclave (for development/testing) ────────────────────────

def _mock_call_enclave(payload: Dict[str, Any]) -> Dict[str, Any]:
    """
    Mock enclave call for development/demo.
      # noqa: W293
    Calls the enclave functions directly instead of vsock.
    This allows the entire system to be tested without AWS Nitro hardware.
    """
    from backend.enclave.enclave_server import (
        classify_sms_enclave,
        classify_voice_enclave,
        get_attestation_document,
    )
      # noqa: E114,E116,W293
    action = payload.get("action", "classify_sms")
      # noqa: E114,E116,W293
    if action == "classify_sms":
        return classify_sms_enclave(payload.get("sms_text", ""))
    elif action == "classify_voice":
        return classify_voice_enclave(payload.get("transcript", ""))
    elif action == "get_attestation":
        return get_attestation_document(
            payload.get("user_data", "").encode()
        )
    else:
        return {"error": f"Unknown action: {action}"}


# ─── Public API ────────────────────────────────────────────────────

def detect_sms_in_enclave(sms_text: str) -> Dict[str, Any]:
    """
    Send SMS text to the enclave for ML-based classification.
      # noqa: W293
    The function transparently handles vsock vs mock mode.
      # noqa: W293
    Args:
        sms_text: The SMS message to classify
      # noqa: W293
    Returns:
        Dict with classification results:
            - label: "SCAM" or "SAFE"
            - confidence: percentage score
            - enclave_processed: bool
    """
    payload = {"action": "classify_sms", "sms_text": sms_text}
      # noqa: E114,E116,W293
    if MOCK_MODE:
        result = _mock_call_enclave(payload)
    else:
        result = call_enclave_vsock(payload)
      # noqa: E114,W293
    result["transport"] = "mock" if MOCK_MODE else "vsock"
    return result


def detect_voice_in_enclave(transcript: str) -> Dict[str, Any]:
    """
    Send voice call transcript to the enclave for vishing detection.
      # noqa: W293
    Args:
        transcript: Voice call transcription text
      # noqa: W293
    Returns:
        Dict with classification results:
            - label: "VISHING" or "SAFE"
            - confidence: percentage score
            - enclave_processed: bool
    """
    payload = {"action": "classify_voice", "transcript": transcript}
      # noqa: E114,E116,W293
    if MOCK_MODE:
        result = _mock_call_enclave(payload)
    else:
        result = call_enclave_vsock(payload)
      # noqa: E114,W293
    result["transport"] = "mock" if MOCK_MODE else "vsock"
    return result


def get_enclave_attestation(user_data: str = "") -> Dict[str, Any]:
    """
    Get attestation document from the Nitro Enclave.
      # noqa: W293
    In production, this cryptographically proves the enclave is genuine
    hardware-backed. Clients can verify the attestation via AWS KMS.
      # noqa: W293
    Args:
        user_data: Optional user-provided data to include in attestation
      # noqa: W293
    Returns:
        Dict with attestation document and PCR values
    """
    payload = {"action": "get_attestation", "user_data": user_data}
      # noqa: E114,E116,W293
    if MOCK_MODE:
        result = _mock_call_enclave(payload)
    else:
        result = call_enclave_vsock(payload)
      # noqa: E114,W293
    return result


def check_enclave_health() -> Dict[str, Union[bool, str]]:
    """
    Check if the enclave is reachable and functional.
      # noqa: W293
    Returns:
        Dict with health status information
    """
    try:
        if MOCK_MODE:
            result = {
                "enclave_reachable": True,
                "mode": "mock",
                "vsock_available": False,
                "note": "Running in mock mode — no hardware enclave",
            }
        else:
            # Quick connectivity test
            call_enclave_vsock({"action": "ping"})
            result = {
                "enclave_reachable": True,
                "mode": "production",
                "vsock_available": True,
            }
    except (ConnectionError, TimeoutError) as e:
        result = {
            "enclave_reachable": False,
            "mode": "production" if not MOCK_MODE else "mock",
            "error": str(e),
        }
      # noqa: E114,W293
    return result  # noqa: W292
