[pytest]
testpaths = .
asyncio_mode = auto
addopts = --cov=backend --cov-report=term-missing --cov-report=html
pythonpath =
markers =
    unit: Unit tests.
    integration: Integration tests.
    e2e: End-to-end tests.
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)