import os
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from datetime import datetime
import hashlib
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding

# Note: In a real app, keys would be managed securely (e.g., AWS KMS)
# For demo, we'll generate/load from local paths
KEYS_DIR = "keys"
PRIVATE_KEY_PATH = f"{KEYS_DIR}/private_key.pem"
PUBLIC_KEY_PATH = f"{KEYS_DIR}/public_key.pem"

def ensure_keys():
    if not os.path.exists(KEYS_DIR):
        os.makedirs(KEYS_DIR)
    
    if not os.path.exists(PRIVATE_KEY_PATH):
        from cryptography.hazmat.primitives.asymmetric import rsa
        private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
        
        with open(PRIVATE_KEY_PATH, "wb") as f:
            f.write(private_key.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.PKCS8,
                encryption_algorithm=serialization.NoEncryption()
            ))
            
        public_key = private_key.public_key()
        with open(PUBLIC_KEY_PATH, "wb") as f:
            f.write(public_key.public_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PublicFormat.SubjectPublicKeyInfo
            ))

def sign_data(data: bytes) -> str:
    ensure_keys()
    with open(PRIVATE_KEY_PATH, "rb") as key_file:
        private_key = serialization.load_pem_private_key(key_file.read(), password=None)
    
    signature = private_key.sign(
        data,
        padding.PSS(mgf=padding.MGF1(hashes.SHA256()), salt_length=padding.PSS.MAX_LENGTH),
        hashes.SHA256()
    )
    return signature.hex()

def generate_fir_pdf(fir_id: int, user_name: str, threat_details: dict) -> tuple[str, str]:
    """
    Generates a digitally signed FIR PDF.
    Returns (file_path, signature)
    """
    output_dir = "static/firs"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        
    file_path = f"{output_dir}/FIR_{fir_id}_{datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"
    
    c = canvas.Canvas(file_path, pagesize=letter)
    width, height = letter
    
    # Register Hindi font if available, otherwise fallback
    # For demo, we'll use Helvetica but add placeholders for Hindi text
    
    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(width/2, height - 50, "FIRST INFORMATION REPORT (DRAFT) / प्रथम सूचना रिपोर्ट")
    c.setFont("Helvetica", 10)
    c.drawCentredString(width/2, height - 65, "Generated by VAS Detection & Prevention System")
    
    # Details
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 100, f"FIR ID / एफआईआर संख्या: {fir_id}")
    c.drawString(50, height - 120, f"Date / दिनांक: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    c.drawString(50, height - 140, f"Complainant / शिकायतकर्ता: {user_name}")
    
    c.line(50, height - 150, width - 50, height - 150)
    
    c.drawString(50, height - 170, "Incident Details / घटना का विवरण:")
    c.setFont("Helvetica", 11)
    c.drawString(70, height - 190, f"Type / प्रकार: {threat_details.get('type')}")
    c.drawString(70, height - 210, f"Source Number / स्रोत संख्या: {threat_details.get('source_number')}")
    c.drawString(70, height - 230, f"Confidence Score / विश्वास स्कोर: {threat_details.get('confidence_score')}")
    
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 260, "Evidence Summary / साक्ष्य सारांश:")
    c.setFont("Helvetica", 11)
    text_object = c.beginText(70, height - 280)
    text_object.setFont("Helvetica", 10)
    content = threat_details.get('content', '')
    lines = [content[i:i+80] for i in range(0, len(content), 80)]
    for line in lines:
        text_object.textLine(line)
    c.drawText(text_object)
    
    # Legal sections
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 400, "Applicable Legal Sections (Suggested) / लागू कानूनी धाराएं:")
    c.setFont("Helvetica", 10)
    c.drawString(70, height - 420, "- Section 66C of IT Act (Identity Theft) / आईटी अधिनियम की धारा 66सी")
    c.drawString(70, height - 440, "- Section 66D of IT Act (Cheating by Personation) / आईटी अधिनियम की धारा 66डी")
    c.drawString(70, height - 460, "- Section 420 of IPC (Cheating) / आईपीसी की धारा 420")
    
    # Signature placeholder
    c.setFont("Helvetica-Bold", 10)
    c.drawString(50, 100, "DIGITAL SIGNATURE / डिजिटल हस्ताक्षर:")
    
    c.save()
    
    # Calculate hash of the generated PDF and sign it
    with open(file_path, "rb") as f:
        pdf_content = f.read()
    
    pdf_hash = hashlib.sha256(pdf_content).digest()
    signature = sign_data(pdf_hash)
    
    # Optionally append signature to PDF metadata or a separate field
    # For now, we return it to be stored in the DB as evidence anchoring
    
    return file_path, signature
